version: "3.3"
services:
  postgres_db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trader
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=trader" ]
      interval: 10s
      timeout: 5s
      retries: 5

  trader_rest_api:
    build:
      context: .
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:9000/actuator/health 2>&1 | grep UP || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 5